### ISSUE TITLE
Centralize service definition as shared settings

### ISSUE THREAD

**Issue by kimcuhoang** [thangchung/practical-dapr#1]
**Problem:**
Currently, every service has its `appsettings.json` in which we have to define services information. Therefore, it's duplicated. 

**Solution:**
- Define `services.json` at solution root
- Then add-as-a-link to `services.json` for every project
- Remember to set **Copy to Output Directory=Always**

**Resources:**
https://andrewlock.net/sharing-appsettings-json-configuration-files-between-projects-in-asp-net-core/

**Comment by thangchung** [comment]
Thanks @kimcu-on-thenet. I will have a look tonight :p

**Comment by thangchung** [comment]
Working great 👍
