### ISSUE TITLE
Question : How can i inject Multi-tenancy to Database and Authentication layer

### ISSUE THREAD

**Issue by shajeeck** [thangchung/practical-dapr#19]
Thank you for awesome repo!

How can i inject request scoped Multi-tenancy to this setup?
Each tenant will have different database and authentication. 
Tenants are identified in HTTP headers.

**Comment by thangchung** [comment]
We don't intend to build the Multi-tenancy app in this repo. But if you want to do that, you can organize it on `identity-server` to store tenant info. And in each service, you can customize the authentication and authorization flows to adopt it. I close it for now
