### ISSUE TITLE
using abp vNext

### ISSUE THREAD

**Issue by xewn** [thangchung/practical-dapr#28]
How do I reuse the module code of  [abp vNext](https://github.com/abpframework/abp) in a dapr environment?

**Comment by thangchung** [comment]
Hi @xewn, thanks for your questions, but I think you could ask this question in the Abp vNext repo so that the team over there will adequate to answer it correctly.

Feel free to re-open this issue, if you want to ask another question related to `dapr` and `tye`. Thank you very much.
