### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by karoldeland** [thangchung/practical-dapr#29]
Hi, 
I would like to know if you are open to contributions and, if so, what would be the opportunities to help you?

My goal is to promote .NET as a cloud-native development platform and I think that your initiative is quite on the edge. I'm looking also at the .NET Containerized eShopOnContainers app.

Some ideas I might think of right now are : 
- Upgrade to .NET 5
- Add documentation on cloud-native patterns
- Making templates out of your work to allow other to start quickly

Let me know what you think if you're willing.

Thank you!

**Comment by thangchung** [comment]
@karoldeland We have been working on https://github.com/thangchung/practical-dapr/tree/feat/shopping-cart-page branch on upgrade to .NET 5
