### ISSUE TITLE
Use IHostedService to migrate database instead of using dotnet ef command

### ISSUE THREAD

**Issue by kimcuhoang** [thangchung/practical-dapr#3]
**Problem:**
- Before firing up `CoolStore.ProductCatalogApi`, it needs to run `dotnet ef database update` mannually.

**Solution:**
- By using `IHostedService` we call `DbContext.Migration` automatically

**Resources:**
https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-3

**Comment by thangchung** [comment]
Cheers!
