### ISSUE TITLE
tye run:  Failed to launch processes 

### ISSUE THREAD

**Issue by valentinmarinro** [thangchung/practical-dapr#32]
I'm unable to figure out this issue, it seems related to tye but, maybe I can get some help here, the containers are created successfully in Docker / Kubernetes but tye is unable to find / start the processes.
I receive below exception for all processes:

> [11:11:13 ERR] Failed to launch process for service productcatalogapi-dapr_df61cb45-b
> System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at Microsoft.Tye.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, Action`1 onStop, CancellationToken cancellationToken) in /_/src/Microsoft.Tye.Core/ProcessUtil.cs:line 117
>    at Microsoft.Tye.Hosting.ProcessRunner.<>c__DisplayClass8_0.<<LaunchService>g__RunApplicationAsync|0>d.MoveNext() in /_/src/Microsoft.Tye.Hosting/ProcessRunner.cs:line 402

This project looks very cool and I really want to experiment with it.

Any ideas would be appreciated.

**Comment by thangchung** [comment]
@valentinmarinro Thanks because you like this project.

What is the version of your `tye` on your local machine?
