### ISSUE TITLE
[GraphQL-HotChocolate] - Use RegisterQueryType & RegisterMutationType instead of RegisterType

### ISSUE THREAD

**Issue by kimcuhoang** [thangchung/practical-dapr#5]
**Problem:**
- we're scanning dll to retrieve all types of `*Type` which are going to be registered for GraphQL by using `RegisterType` extension

**Solution:**
Hot Chocolate has supported to register for **QueryType** and **MutationType**

**Comment by thangchung** [comment]
On PR #9 already
