### ISSUE TITLE
[EfCore] Warning of Remove the 'AddEntityFramework*' call ...

### ISSUE THREAD

**Issue by kimcuhoang** [thangchung/practical-dapr#6]
**Problem:**

This is a breaking change from .NET Core 3.0, see the link below

https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#addentityframework-adds-imemorycache-with-a-size-limit

**Solution:**
Remove the call of `AddEntityFramework`

**Comment by thangchung** [comment]
Fixed on #9 with your PR
